# Take Home Problems 2 - Mariia Onokhina

## Numpy

In [1]:
import numpy as np

1. Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.

In [23]:
A = np.array([1, 2, 3, 4, 5, 6, 7])
B = np.array([3, 4, 5, 6, 7, 8, 9])

In [24]:
# Vertical stack
v_stack = np.vstack((A, B))
v_stack

array([[1, 2, 3, 4, 5, 6, 7],
       [3, 4, 5, 6, 7, 8, 9]])

In [25]:
# Horizontal stack
h_stack = np.hstack((A, B))
h_stack

array([1, 2, 3, 4, 5, 6, 7, 3, 4, 5, 6, 7, 8, 9])

2. Find common elements between A and B. [Hint: Intersection of two sets]

In [26]:
# Find intersection manually
seen = set(A)
result = []

for item in B:
    if item in seen:
        result.append(item)

result = np.array(result)
result

array([3, 4, 5, 6, 7])

In [27]:
# Use numpy method
# https://numpy.org/doc/2.3/reference/generated/numpy.intersect1d.html
result = np.intersect1d(A, B)
result

array([3, 4, 5, 6, 7])

3. Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]

In [31]:
# Extract even numbers
A[np.where(A % 2 == 0)]

array([2, 4, 6])

4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

In [32]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [42]:
iris_2d[np.where((iris_2d[:,2] > 1.5) & (iris_2d[:,0] < 5.0))]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

## Pandas

In [43]:
import pandas as pd

1. From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

In [44]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 27 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Manufacturer        89 non-null     object 
 1   Model               92 non-null     object 
 2   Type                90 non-null     object 
 3   Min.Price           86 non-null     float64
 4   Price               91 non-null     float64
 5   Max.Price           88 non-null     float64
 6   MPG.city            84 non-null     float64
 7   MPG.highway         91 non-null     float64
 8   AirBags             55 non-null     object 
 9   DriveTrain          86 non-null     object 
 10  Cylinders           88 non-null     object 
 11  EngineSize          91 non-null     float64
 12  Horsepower          86 non-null     float64
 13  RPM                 90 non-null     float64
 14  Rev.per.mile        87 non-null     float64
 15  Man.trans.avail     88 non-null     object 
 16  Fuel.tank.

In [56]:
df.head()

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura  Integra    Small       12.9   15.9       18.8      25.0   
1          NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2         Audi       90  Compact       25.9   29.1       32.3      20.0   
3         Audi      100  Midsize        NaN   37.7       44.6      19.0   
4          BMW     535i  Midsize        NaN   30.0        NaN      22.0   

   MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                 NaN      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186.0   

   Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0      102.0   68.0         37.0           26.5           NaN  2705.0   
1      115.0   71.0         38.0           30.0          15.0  3560.0   
2      102.0   67.0         37.0           28.0          14.0  3375.0   
3      106.0    NaN         37.0           31.0          17.0  3405.0   
4      109.0   69.0         39.0           27.0          13.0  3640.0   

    Origin           Make  
0  non-USA  Acura Integra  
1  non-USA   Acura Legend  
2  non-USA        Audi 90  
3  non-USA       Audi 100  
4  non-USA       BMW 535i  

[5 rows x 27 columns]

In [62]:
df[["Manufacturer", "Model", "Type"]].iloc[::20]

Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

2. Replace missing values in Min.Price and Max.Price columns with their respective mean.

In [84]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [85]:
min_price_mean = df["Min.Price"].mean()
min_price_mean

np.float64(17.118604651162787)

In [86]:
max_price_mean = df["Max.Price"].mean()
max_price_mean

np.float64(21.45909090909091)

In [89]:
df["Min.Price"] = df["Min.Price"].fillna(min_price_mean)
df["Max.Price"] = df["Max.Price"].fillna(max_price_mean)

3. How to get the rows of a dataframe with row sum > 100?

In [91]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

In [93]:
df

0   1   2   3
0   33  10  10  25
1   17  27  37  33
2   11  14  29  25
3   39  16  13  15
4   13  10  27  12
5   18  37  22  16
6   15  14  21  17
7   30  24  10  12
8   14  27  33  39
9   34  21  17  38
10  17  12  14  34
11  12  35  34  28
12  16  36  17  20
13  19  30  34  24
14  12  29  30  19

In [97]:
df[df.sum(axis=1) > 100]

0   1   2   3
1   17  27  37  33
8   14  27  33  39
9   34  21  17  38
11  12  35  34  28
13  19  30  34  24